@host=https://httpdump.app/dumps/c6729da5-ab5a-499a-97c7-932f815489e9
###############
# @name login
POST {{host}}/oauth/token
Content-Type: application/json
Accept: application/json

{
    "grant_type": "password",
    "username": "test@example.com",
    "password": "password",
    "client_id": "2",
    "client_secret": "cS9ya8RnIiqYRBMbA848qtSpFpoz1OPKfrIpGofk",
    "scope": "*"
}
##############
@bearer = {{login.response.body.access_token}}
@product_id =
@product_name =
@product_description =
######################
# @name ListProduct
GET {{host}}/api/product
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE
#######################
# @name CreateProduct
POST {{host}}/api/product
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "name":"{{product_name}}",
    "description":"{{product_description}}"
}
######################
# @name ShowProduct
GET {{host}}/api/product/{{product_id}}
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE
######################
# @name UpdateProduct
PUT {{host}}/api/product/{{product_id}}
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "name":"{{product_name}}",
    "description":"{{product_description}}"
}
######################
# @name DeleteProduct
DELETE {{host}}/api/product/{{product_id}}
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE