###############
# @name Auth
POST {{host}}/oauth/token
Content-Type: application/json
Accept: application/json

{
    "grant_type":"password",
    "client_id":"{{client_id}}",
    "client_secret":"{{client_secret}}",
    "username":"{{username}}",
    "password":"{{password}}",
    "scope":"*"
}
##############
@bearer = {{Auth.response.body.access_token}}
@product_id=1
@product_name=productname
@product_description=description
######################
# @name ListProduct
GET {{host}}/api/product
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE
#######################
# @name CreateProduct
POST {{host}}/api/product
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "name":"{{product_name}}",
    "description":"{{product_description}}"
}
######################
# @name ShowProduct
GET {{host}}/api/product/{{product_id}}
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE
######################
# @name UpdateProduct
PUT {{host}}/api/product/{{product_id}}
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE

{
    "name":"{{product_name}}",
    "description":"{{product_description}}"
}
######################
# @name DeleteProduct
DELETE {{host}}/api/product/{{product_id}}
Authorization: Bearer {{bearer}}
Accept: application/json
Content-Type: application/json
Cookie: XDEBUG_SESSION=XDEBUG_ECLIPSE